---
fixtures:
  repositories:
    augeasproviders_core: "git://github.com/simp/augeasproviders_core"
    augeasproviders_grub: "git://github.com/simp/augeasproviders_grub"
    auditd: "git://github.com/simp/pupmod-simp-auditd"
    simplib: "git://github.com/simp/pupmod-simp-simplib"
    simpcat: "git://github.com/simp/pupmod-simp-concat"
    openldap: "git://github.com/simp/pupmod-simp-openldap"
    pki: "git://github.com/simp/pupmod-simp-pki"
    sssd: "git://github.com/simp/pupmod-simp-sssd"
    stdlib: "git://github.com/simp/puppetlabs-stdlib"
  symlinks:
    nscd: "#{source_dir}"
